import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../src/engine.js';
import * as P from '../src/physics.js';
function arena(rounds=14) {const s=E.createGame(rounds);s.cells.fill(0);s.towers=[];s.players[1].pos={x:8,y:10};s.players[2].pos={x:12,y:16};E.recompute(s);return s;}
function tower(s,owner,x,y,stage=1,state='normal') {const t={id:++s.nextId,owner,pos:{x,y},stage,state,slot:'ABCDE'[s.towers.filter(t=>t.owner===owner).length],protected:[],relayUsed:false};s.towers.push(t);E.expand(s,t);E.recompute(s);return t;}
function advance(s) {assert.ok(E.endTurn(s));assert.ok(E.beginTurn(s));}
function readyTake(s,stage=1) {const t=tower(s,2,8,10,stage);t.state='overloaded';t.overloadExpiresTurn=s.turnIndex+1;s.players[1].pos={x:7,y:10};E.recompute(s);return t;}
for(const n of [10,14,18]) test(`mode ${n} uses matching max HP`,()=>{const s=E.createGame(n);assert.equal(s.maxRounds,n);for(const p of Object.values(s.players)){assert.equal(p.hp,n);assert.equal(p.maxHp,n);}});
for(const n of [1,20,100,0,NaN]) test(`unsupported mode ${n} rejected`,()=>assert.throws(()=>E.createGame(n)));
test('default Standard HP is fourteen',()=>assert.equal(E.createGame().players[1].hp,14));
test('missile relay overload keeps charge and history, removes protection and stable root',()=>{const s=arena(),t=tower(s,1,8,10);E.chooseAim(s,'missile');s.players[1].pos={x:6,y:10};P.launch(s,{x:1,y:0},.3);for(let i=0;i<200&&s.activeBody;i++)P.stepBody(s,1/120);assert.equal(s.phase,'MISSILE_RELAY_AIM');assert.equal(t.state,'overloaded');assert.equal(s.charge,1);assert.ok(s.visitedRelayTowerIds.has(t.id));assert.equal(t.protected.length,0);assert.equal(s.stability[E.index(s,t.pos)],'temporary');assert.equal(E.relayStatus(s,t),'normal');assert.equal(t.owner,1);assert.ok(s.towers.includes(t));});
test('vanguard relay never overloads',()=>{const s=arena(),t=tower(s,1,8,10);s.players[1].pos={x:6,y:10};E.chooseAim(s,'move');P.launch(s,{x:1,y:0},.3);for(let i=0;i<200&&s.activeBody;i++)P.stepBody(s,1/120);assert.equal(s.phase,'MOVE_RELAY_AIM');assert.equal(t.state,'normal');});
for(const state of ['normal','overloaded','contested'])test(`external ${state} source immunity`,()=>{const s=arena(),a=tower(s,1,8,10),b=tower(s,1,9,10,1,state);assert.equal(typeof E.applyRelayOverload,'function');E.applyRelayOverload(s,a);assert.equal(a.state,state==='normal'?'normal':'overloaded');});
test('own protection cannot suppress overload',()=>{const s=arena(),a=tower(s,1,8,10);assert.equal(typeof E.applyRelayOverload,'function');E.applyRelayOverload(s,a);assert.equal(a.state,'overloaded');});
test('overload grants entire opposing turn and recovery defers owner growth',()=>{const s=arena(),a=tower(s,1,8,10);assert.equal(typeof E.applyRelayOverload,'function');E.applyRelayOverload(s,a);const cells=[...s.cells];advance(s);assert.equal(a.state,'overloaded');advance(s);assert.equal(a.state,'normal');assert.equal(a.stage,1);assert.equal(s.cells[E.index(s,a.pos)],1);assert.ok(a.protected.length);assert.ok(cells.some(c=>c===1));});
for(const stage of [0,1,2])test(`takeover maturity stage ${stage}`,()=>{const s=arena(),a=readyTake(s,stage);assert.equal(typeof E.getTakeoverCandidates,'function');assert.equal(E.getTakeoverCandidates(s).includes(a),stage>0);});
test('normal enemy tower cannot be taken over',()=>{const s=arena(),a=readyTake(s);a.state='normal';E.recompute(s);assert.equal(typeof E.getTakeoverCandidates,'function');assert.equal(E.getTakeoverCandidates(s).length,0);});
test('other enemy protection of foot tile prevents takeover',()=>{const s=arena(),a=readyTake(s);tower(s,2,6,10);assert.equal(typeof E.getTakeoverCandidates,'function');assert.equal(E.getTakeoverCandidates(s).includes(a),false);});
test('other enemy protection of tower center prevents takeover',()=>{const s=arena(),a=readyTake(s);tower(s,2,9,10);assert.equal(typeof E.getTakeoverCandidates,'function');assert.equal(E.getTakeoverCandidates(s).includes(a),false);});
test('spent action prevents takeover',()=>{const s=arena();readyTake(s);s.actionAvailable=false;assert.equal(typeof E.getTakeoverCandidates,'function');assert.equal(E.getTakeoverCandidates(s).length,0);});
test('expired overload cannot be taken over',()=>{const s=arena(),a=readyTake(s);a.overloadExpiresTurn=0;assert.equal(typeof E.getTakeoverCandidates,'function');assert.equal(E.getTakeoverCandidates(s).length,0);});
test('takeover is contested, terminal, nonhealing, inactive and still old owner',()=>{const s=arena(),a=readyTake(s);s.players[1].hp=9;assert.equal(typeof E.startTakeover,'function');assert.ok(E.startTakeover(s,a.id));assert.equal(a.state,'contested');assert.equal(a.owner,2);assert.equal(s.phase,'HANDOFF');assert.equal(s.current,2);assert.equal(s.actionAvailable,false);assert.equal(s.moveAvailable,false);assert.equal(s.players[1].hp,9);E.beginTurn(s);assert.equal(a.state,'contested');assert.equal(a.stage,1);assert.equal(a.protected.length,0);assert.equal(s.stability[E.index(s,a.pos)],'temporary');});
test('contested cannot be redeployed away',()=>{const s=arena(),a=readyTake(s);a.state='contested';a.owner=1;for(let i=0;i<4;i++)tower(s,1,2+i*2,4,0);s.players[1].pos={x:4,y:20};assert.equal(E.buildTower(s,a.slot),false);assert.ok(s.towers.includes(a));});
test('reclaim restores without repaint and terminates turn',()=>{const s=arena(),a=readyTake(s);assert.equal(typeof E.startTakeover,'function');E.startTakeover(s,a.id);E.beginTurn(s);s.players[2].pos={x:9,y:10};const before=[...s.cells];assert.ok(E.reclaimTower(s,a.id));assert.equal(a.state,'normal');assert.equal(a.owner,2);assert.deepEqual(s.cells,before);assert.ok(a.protected.length);assert.equal(s.phase,'HANDOFF');E.beginTurn(s);assert.equal(a.owner,2);});
for(const stage of [1,2])test(`takeover completion stage ${stage} retained, growth deferred`,()=>{const s=arena(),a=readyTake(s,stage);assert.equal(typeof E.startTakeover,'function');E.startTakeover(s,a.id);E.beginTurn(s);advance(s);assert.equal(a.owner,1);assert.equal(a.state,'normal');assert.equal(a.stage,stage);assert.equal(s.cells[E.index(s,a.pos)],1);const stamp=a.activationTurn;advance(s);advance(s);assert.equal(a.stage,2);assert.equal(a.activationTurn,stamp);});
test('five owned towers require normal replacement and fail atomically',()=>{const s=arena(),a=readyTake(s);for(let i=0;i<5;i++)tower(s,1,1+i*2,3,0);const before=structuredClone(s.towers);assert.equal(typeof E.startTakeover,'function');assert.equal(E.startTakeover(s,a.id),false);assert.deepEqual(s.towers,before);assert.equal(E.startTakeover(s,a.id,999),false);assert.deepEqual(s.towers,before);const replace=s.towers.find(t=>t.owner===1);replace.state='contested';assert.equal(E.startTakeover(s,a.id,replace.id),false);replace.state='normal';assert.ok(E.startTakeover(s,a.id,replace.id));assert.equal(s.towers.filter(t=>t.owner===1).length,4);E.beginTurn(s);advance(s);assert.equal(s.towers.filter(t=>t.owner===1).length,5);});
test('contextual operation chooses reclaim, takeover, redeploy, deploy',()=>{const s=arena(),a=readyTake(s);assert.equal(typeof E.outpostAction,'function');assert.equal(E.outpostAction(s).kind,'takeover');a.state='contested';a.owner=1;assert.equal(E.outpostAction(s).kind,'reclaim');a.state='normal';assert.equal(E.outpostAction(s).kind,'deploy');for(let i=0;i<4;i++)tower(s,1,2+i*2,4,0);assert.equal(E.outpostAction(s).kind,'redeploy');});
test('multi-target overlap returns only legal overloaded mature towers',()=>{const s=arena(),a=readyTake(s),b=tower(s,2,6,10,1,'overloaded');b.overloadExpiresTurn=1;assert.equal(typeof E.getTakeoverCandidates,'function');assert.deepEqual(E.getTakeoverCandidates(s).map(t=>t.id),[a.id,b.id]);});
test('activation protected tiles excluded and external growth never creates insertion pending',()=>{const s=arena(),a=readyTake(s,2),b=tower(s,2,5,10,2);s.players[1].pos={x:9,y:10};assert.equal(typeof E.startTakeover,'function');assert.ok(E.startTakeover(s,a.id));E.beginTurn(s);advance(s);assert.equal(a.owner,1);assert.equal(s.cells[E.index(s,{x:6,y:10})],2);assert.ok(s.protectedBy[E.index(s,{x:6,y:10})].includes(b.id));assert.equal(s.claims.length,0);});
test('takeover split establishes current components then delayed dynamic capture',()=>{const s=arena(),a=readyTake(s,2);for(let x=1;x<16;x++)s.cells[E.index(s,{x,y:10})]=2;E.recompute(s);assert.equal(typeof E.startTakeover,'function');assert.ok(E.startTakeover(s,a.id));E.beginTurn(s);advance(s);assert.equal(s.claims.length,2);for(const c of s.claims){assert.equal(c.dueTurn,s.turnIndex+2);assert.ok(c.cells.every(i=>s.cells[i]===2&&s.stability[i]==='temporary'));}assert.equal(s.cells[E.index(s,{x:2,y:10})],2);const extra=E.index(s,{x:2,y:11});s.cells[extra]=2;E.recompute(s);assert.ok(s.claims.some(c=>c.cells.includes(extra)));advance(s);advance(s);assert.equal(s.cells[extra],1);assert.equal(s.cells[E.index(s,{x:2,y:10})],1);assert.equal(s.claims.length,0);});
test('restoring an enemy root cancels its pending region',()=>{const s=arena(),a=readyTake(s,2);for(let x=1;x<16;x++)s.cells[E.index(s,{x,y:10})]=2;E.recompute(s);assert.equal(typeof E.startTakeover,'function');E.startTakeover(s,a.id);E.beginTurn(s);advance(s);tower(s,2,2,10,0);assert.equal(s.claims.length,1);assert.ok(s.claims[0].cells.every(i=>i%s.width>10));});
test('final round does not accelerate future contested settlement',()=>{const s=arena(10),a=readyTake(s);s.current=2;s.round=10;a.owner=1;a.overloadExpiresTurn=1;E.recompute(s);s.players[2].pos={x:7,y:10};s.players[1].pos={x:2,y:20};assert.equal(typeof E.startTakeover,'function');assert.ok(E.startTakeover(s,a.id));assert.ok(s.winner);assert.equal(a.owner,1);assert.equal(E.beginTurn(s),false);});
test('multiple protection sources survive one overload',()=>{const s=arena(),a=tower(s,1,8,10),b=tower(s,1,9,10);const i=E.index(s,{x:8,y:10});assert.equal(s.protectedBy[i].length,2);a.state='overloaded';E.recompute(s);assert.deepEqual(s.protectedBy[i],[b.id]);assert.equal(s.stability[i],'stable');});
test('new painted land immediately follows connectivity',()=>{const s=arena(),a=tower(s,1,8,10,0);E.paintMissile(s,1,{x:9,y:10},0);assert.equal(s.stability[E.index(s,{x:10,y:10})],'stable');E.paintMissile(s,1,{x:3,y:20},0);assert.equal(s.stability[E.index(s,{x:3,y:20})],'temporary');assert.equal(s.stability[0],null);});
